### ISSUE TITLE
Set Up The First Ever Version of the Database

### ISSUE THREAD

**Issue by nickwxo** [slashroots/undp-ghg#15]
As an Inventory Manager I want to be able to set up the first ever version of the database so that the team have access to the empty structure of the DB to upload data and populate with input variables and calculations for the first time.

Acceptance Criteria : 

- Can populate all required years of the timeseries with variables needed to calculate emissions for all categories and sectors for all gases
- Can set-up suitible calculations that apply the different variables to estimate emissions and removals.  Minimum requirements for calculation should be e.g. input variable X * input variable Y = output variable Z for each year of the timeseries present in the database.

**Comment by paradoxxjm** [comment]
Closing ticket as it is a duplication of #27 .
