### ISSUE TITLE
Set up a new version of GHG Inventory

### ISSUE THREAD

**Issue by nickwxo** [slashroots/undp-ghg#17]
As as Inventory Manager or System Administrator I want to be able to set up a new version of the GHG Inventory so that the team can begin to work on a new version of the GHG inventory and retain a carbon copy frozen archive of the previous version.

Acceptance Criteria : 

- All activity data and emissions figures and other notes, notations, justifications, assumptions, and calculated uncertainties, documentation, formulae/calculations/outputs etc for all sectors, categories, and greenhouse gases have been saved to an archive version or are copied to a new version without any loss of information.
-The new version is editable.  The archive version is not editable without the defined exception authorisation being provided by Inventory Manager or System Administrator only.

**Comment by densoutar** [comment]
Closed due to duplication of #27

**Comment by denferg** [comment]
Closed due to duplication of #27
